// fe-react/src/components/QuotesListItem/QuotesListItem.tsx
import classNames from "classnames";
import appConfig from "../../config/appConfig";
import { QuotesListItemProps } from "./QuotesListItem.types";
import TextButton from "../TextButton/TextButton";
import { CopyStatus } from "../../constants";
import ClipboardIcon from "../Heroicons/ClipboardIcon";

export default function QuotesListItem({
	quote,
	itemIndex,
	copyStatus,
	className,
	onClickCopy,
}: QuotesListItemProps) {
	const author = quote.author || appConfig.authorDefaultName;

	return (
		<li
			data-before={itemIndex}
			className={classNames(
				"py-4",
				"border-t border-dashed border-t-slate-400 first:border-none before:content-[attr(data-before)] before:text-slate-500 before:bg-slate-100 before:rounded-full before:w-8 before:h-8 before:inline-flex before:justify-center before:items-center",
				className
			)}
		>
			<TextButton
				testid="copy-to-clipboard-button"
				title="Copy to clipboard"
				aria-label="Copy to clipboard"
				className="text-sm float-right h-8 flex items-center gap-1"
				colorClassName={classNames({
					"text-green-700": copyStatus === CopyStatus.copied,
					"text-red-700": copyStatus === CopyStatus.error,
				})}
				disabled={copyStatus !== CopyStatus.waiting}
				onClick={() => onClickCopy()}
			>
				{copyStatus === CopyStatus.copied ? (
					<span>Copied</span>
				) : (
					copyStatus === CopyStatus.error && <span>Error</span>
				)}
				<ClipboardIcon />
			</TextButton>
			<figure className="px-4 py-1">
				<blockquote className="quotes">{quote.content?.trim()}</blockquote>
				<figcaption className="text-right text-sm font-medium mt-2 before:content-['by'] before:text-gray-400 before:mr-1 before:font-normal">
					{author}
				</figcaption>
			</figure>
		</li>
	);
}

// fe-angular/src/app/components/quotes-list-item/quotes-list-item.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { Quote } from "../../types/quotes";
import { CopyStatus, EMPTY_STRING } from "../../constants";
import appConfig from "../../config/appConfig";

@Component({
	selector: "app-quotes-list-item",
	templateUrl: "./quotes-list-item.component.html",
	styleUrl: "./quotes-list-item.component.scss",
})
export class QuotesListItemComponent {
	@Input({ required: true }) quote = {} as Quote;
	@Input({ required: true }) itemIndex = 1;
	@Input() class = EMPTY_STRING;
	@Input() copyStatus: CopyStatus | null = null;
	@Output() onClickCopy = new EventEmitter<Quote>();

	readonly copyStati = CopyStatus;
	readonly authorDefaultName = appConfig.authorDefaultName;

	handlerClickCopy() {
		this.onClickCopy.emit(this.quote);
	}

	isCopyStatus(status: CopyStatus) {
		if (this.copyStatus === null) {
			return status === this.copyStati.waiting;
		}

		return status === this.copyStatus;
	}
}

<li [attr.data-before]="itemIndex" class="pt-1 pb-1" [ngClass]="class">
	<button
		type="button"
		title="Copy to clipboard"
		class="copy-button text-sm flex items-center gap-1/2"
		[ngClass]="{
			success: isCopyStatus(copyStati.copied),
			error: isCopyStatus(copyStati.error),
		}"
		(click)="handlerClickCopy()"
	>
		<span *ngIf="isCopyStatus(copyStati.copied)">Copied</span>
		<span *ngIf="isCopyStatus(copyStati.error)">Error</span>
		<mat-icon>content_copy</mat-icon>
	</button>
	<figure class="m-0 pt-1/2 pb-1/2 pr-1 pl-1">
		<blockquote class="m-0 quotes">{{ quote.content.trim() }}</blockquote>
		<figcaption
			data-before="by"
			class="text-right text-sm font-medium mt-1/2 before:text-gray-400 before:mr-1 before:font-normal"
		>
			{{ quote.author || authorDefaultName }}
		</figcaption>
	</figure>
</li>
