// fe-react/src/pages/LoginPage.tsx
import { Helmet } from "react-helmet-async";
import AuthLayout from "../components/AuthLayout/AuthLayout";
import RouterLink from "../components/RouterLink/RouterLink";
import { pageItems } from "../config/pageItems";
import AuthForm from "../components/AuthForm/AuthForm";
import { AuthFormValues } from "../components/AuthForm/AuthForm.types";
import { useAuth } from "../hooks/auth";
import AuthFormTitle from "../components/AuthFormTitle/AuthFormTitle";

export default function LoginPage() {
	const { isMutating, errorMessage, doLogin } = useAuth();

	const handleOnSubmit = (formValues: AuthFormValues) => {
		doLogin(formValues);
	};

	return (
		<AuthLayout>
			<Helmet>
				<title>{pageItems.login.pageTitle}</title>
			</Helmet>
			<AuthFormTitle>{pageItems.login.pageTitle}</AuthFormTitle>
			<AuthForm
				type="login"
				errorMessage={errorMessage}
				isLoading={isMutating}
				onSubmit={handleOnSubmit}
			/>
			<p>
				Need an account? <RouterLink to="/signup">Sign up</RouterLink>
			</p>
		</AuthLayout>
	);
}

// fe-angular/src/app/pages/login-page/login-page.component.ts
import { Component } from "@angular/core";
import { pageItems } from "../../config/pageItems";
import { AuthFormValues } from "../../types/auth";

@Component({
	selector: "app-login-page",
	templateUrl: "./login-page.component.html",
	styleUrl: "./login-page.component.scss",
})
export class LoginPageComponent {
	readonly pageItems = pageItems;
	isLoading = false;

	onSubmit(values: AuthFormValues) {
		this.isLoading = true;

		console.log(values);
		setTimeout(() => {
			this.isLoading = false;
		}, 2000);
	}
}

<app-auth-layout>
	<app-auth-form-title>{{ pageItems.login.pageTitle }}</app-auth-form-title>
	<app-auth-form type="login" [isLoading]="isLoading" (onSubmit)="onSubmit($event)" />
	<p>Need an account? <a [routerLink]="pageItems.signup.url">Sign up</a></p>
</app-auth-layout>
