// fe-react/src/components/QuotesList/QuotesList.tsx
import { ChangeEvent, useCallback, useEffect, useState } from "react";
import classNames from "classnames";
import { useQuotes } from "../../hooks/quotes";
import Card from "../Card/Card";
import QuotesListItem from "../QuotesListItem/QuotesListItem";
import PaginationMenu from "../PaginationMenu/PaginationMenu";
import appConfig from "../../config/appConfig";
import ErrorMessage from "../ErrorMessage/ErrorMessage";
import { CopyStatus, EMPTY_STRING } from "../../constants";
import { Quote } from "../../types/quotes";
import TextField from "../TextField/TextField";
import { useThrottle } from "../../hooks/throttle";
import { useTimer } from "../../hooks/timer";

export default function QuotesList() {
	const { throttle } = useThrottle();
	const { quotes, mainQueryState, pagination, refreshQuotes } = useQuotes();

	const { setTimer: setCopiedTimer } = useTimer();
	const { setTimer: setSearchTimer } = useTimer();
	const [copyStatus, setCopyStatus] = useState(CopyStatus.waiting);
	const [copiedQuoteId, setCopiedQuoteId] = useState<string | null>(null);
	const [searchString, setSearchString] = useState(EMPTY_STRING);
	const [showSearchField, setShowSearchField] = useState(Boolean(quotes.length));
	const [isSearching, setIsSearching] = useState(false);

	const handleOnChangeSearchString = useCallback(
		(event: ChangeEvent<HTMLInputElement>) => {
			const value = event.target.value;
			const trimmedValue = value.trim();
			const triggerSearch = () => refreshQuotes(1, { keywords: trimmedValue });

			setSearchString(value);

			if (!trimmedValue) {
				triggerSearch();

				return;
			}

			setIsSearching(true);
			throttle(triggerSearch, 1000);

			setSearchTimer(() => {
				setIsSearching(false);
			}, 1000);
		},
		[refreshQuotes, throttle, setSearchTimer]
	);

	const copyToClipboard = useCallback(
		async (quote: Quote) => {
			setCopiedQuoteId(quote.id);

			try {
				if (!("clipboard" in navigator)) {
					throw new Error();
				}

				const author = quote.author || appConfig.authorDefaultName;

				await navigator.clipboard.writeText(`${quote.content}\n( ${author} )`);

				setCopyStatus(CopyStatus.copied);
			} catch {
				setCopyStatus(CopyStatus.error);
			}

			setCopiedTimer(() => {
				setCopyStatus(CopyStatus.waiting);
			}, appConfig.feedbackTimeout);
		},
		[setCopiedTimer]
	);

	useEffect(() => {
		if (quotes.length && !showSearchField) {
			setShowSearchField(true);
		}
	}, [showSearchField, quotes.length]);

	useEffect(() => {
		if (!mainQueryState.searchFilters.keywords) {
			setSearchString(EMPTY_STRING);
		}
	}, [mainQueryState.searchFilters.keywords]);

	const onClickRefresh = () => {
		location.reload();
	};

	return (
		<Card title="Your saved quotes">
			{mainQueryState.isError && (
				<ErrorMessage className="mt-8">
					{"Something didn't work. Please try to "}
					<button type="button" className="underline" onClick={onClickRefresh}>
						refresh the page
					</button>
					{"."}
				</ErrorMessage>
			)}
			{showSearchField && (
				<TextField
					type="search"
					name="searchKeywords"
					outerClassName="mb-4"
					placeholder="Search by keywords"
					value={searchString}
					onChange={handleOnChangeSearchString}
				/>
			)}
			{mainQueryState.isLoading ? (
				<p className="text-gray-500 text-sm mt-6 mb-2">Quotes are loading...</p>
			) : !quotes.length && isSearching ? (
				<p className="text-gray-500 text-sm mt-6 mb-2">Searching...</p>
			) : !quotes.length ? (
				<p className="text-sm mt-6 mb-2">No quotes found.</p>
			) : (
				<>
					<ol
						data-testid="quotes-list"
						className={classNames({
							"opacity-50": isSearching || mainQueryState.isRefetching,
						})}
					>
						{quotes.map((quote, idx) => {
							const itemNum = idx + 1 + (pagination.currentPage - 1) * appConfig.quotesPerPage;

							return (
								<QuotesListItem
									key={`QuoteItem_${quote.id}`}
									quote={quote}
									itemIndex={itemNum}
									copyStatus={copiedQuoteId === quote.id ? copyStatus : CopyStatus.waiting}
									onClickCopy={() => copyToClipboard(quote)}
								/>
							);
						})}
					</ol>
					<PaginationMenu
						className="mt-6 mb-2"
						currentPage={pagination.currentPage}
						numOfQuotes={pagination.totalCount}
						onClick={page => refreshQuotes(page, { keywords: searchString.trim() })}
					/>
				</>
			)}
		</Card>
	);
}

// fe-angular/src/app/components/quotes-list/quotes-list.component.ts
import { Component, Input, OnChanges, OnDestroy, OnInit, SimpleChanges } from "@angular/core";
import {
	asyncScheduler,
	BehaviorSubject,
	delay,
	filter,
	map,
	of,
	Subject,
	switchMap,
	takeUntil,
	tap,
	throttleTime,
} from "rxjs";
import { Quote } from "../../types/quotes";
import { Store } from "@ngrx/store";
import { AppState } from "../../store";
import { loadQuotes } from "../../store/actions/quotes.actions";
import {
	selectDisplayedQuotes,
	selectIsFetchError,
	selectIsLoadingQuotes,
	selectPagination,
} from "../../store/selectors/quotes.selectors";
import appConfig from "../../config/appConfig";
import { FormControl, ReactiveFormsModule } from "@angular/forms";
import { CopyStatus, EMPTY_STRING } from "../../constants";
import { Clipboard } from "@angular/cdk/clipboard";
import { MatCardModule } from "@angular/material/card";
import { ErrorMessageComponent } from "../error-message/error-message.component";
import { MatFormFieldModule } from "@angular/material/form-field";
import { CommonModule } from "@angular/common";
import { QuotesListItemComponent } from "../quotes-list-item/quotes-list-item.component";
import { PaginationMenuComponent } from "../pagination-menu/pagination-menu.component";
import { MatInputModule } from "@angular/material/input";

@Component({
	standalone: true,
	selector: "app-quotes-list",
	templateUrl: "./quotes-list.component.html",
	styleUrl: "./quotes-list.component.scss",
	imports: [
		CommonModule,
		ReactiveFormsModule,
		MatCardModule,
		MatFormFieldModule,
		MatInputModule,
		ErrorMessageComponent,
		QuotesListItemComponent,
		PaginationMenuComponent,
	],
})
export class QuotesListComponent implements OnInit, OnChanges, OnDestroy {
	quotes: Quote[] = [];
	showSearchField = false;
	copyQuoteId = EMPTY_STRING;

	@Input() resetSearchNeedleCounter = 0;

	readonly isLoading$ = this.store.select(selectIsLoadingQuotes);
	readonly isError$ = this.store.select(selectIsFetchError);
	readonly pagination$ = this.store.select(selectPagination);
	readonly destroySbj$ = new Subject();
	readonly isSearchingSbj$ = new BehaviorSubject(false);
	readonly copyStatusSbj$ = new BehaviorSubject(CopyStatus.waiting);
	readonly searchField = new FormControl(EMPTY_STRING, { nonNullable: true });

	constructor(
		private store: Store<AppState>,
		private clipboard: Clipboard
	) {}

	ngOnInit(): void {
		this.subscribeToStore();
		this.subscribeToSearchNeedleChanges();

		this.copyStatusSbj$
			.pipe(
				filter(value => value !== CopyStatus.waiting),
				switchMap(value => of(value).pipe(delay(appConfig.feedbackTimeout))),
				takeUntil(this.destroySbj$)
			)
			.subscribe(() => {
				this.copyStatusSbj$.next(CopyStatus.waiting);
			});
	}

	ngOnChanges(changes: SimpleChanges): void {
		const resetCounterChanges = changes["resetSearchNeedleCounter"] || {};

		if (resetCounterChanges.currentValue != resetCounterChanges.previousValue) {
			this.searchField.setValue(EMPTY_STRING, { emitEvent: false });
		}
	}

	ngOnDestroy(): void {
		this.destroySbj$.next(true);
		this.destroySbj$.complete();
	}

	private subscribeToStore() {
		this.store.dispatch(loadQuotes({ page: 1 }));
		this.store
			.select(selectDisplayedQuotes)
			.pipe(takeUntil(this.destroySbj$))
			.subscribe(quotes => {
				this.quotes = quotes;

				if (quotes.length) {
					this.showSearchField = true;
				}
			});
	}

	private subscribeToSearchNeedleChanges() {
		this.searchField.valueChanges
			.pipe(
				map(value => value.trim()),
				tap(value => {
					if (!value) {
						this.store.dispatch(loadQuotes({ page: 1 }));
					}
				}),
				filter(Boolean),
				throttleTime(2000, asyncScheduler, { leading: true, trailing: true }),
				takeUntil(this.destroySbj$)
			)
			.subscribe(searchNeedle => {
				if (!this.searchField.value.trim()) {
					return;
				}

				this.store.dispatch(
					loadQuotes({
						page: 1,
						refetch: true,
						filters: { searchNeedle },
					})
				);
			});

		this.searchField.valueChanges
			.pipe(
				map(value => Boolean(value.trim())),
				takeUntil(this.destroySbj$)
			)
			.subscribe(this.isSearchingSbj$);

		this.isSearchingSbj$
			.pipe(
				filter(Boolean),
				switchMap(value => of(value).pipe(delay(1000))),
				takeUntil(this.destroySbj$)
			)
			.subscribe(() => {
				this.isSearchingSbj$.next(false);
			});
	}

	handleClickPagination(page: number) {
		const searchNeedle = this.searchField.value.trim();
		const filters = searchNeedle ? { searchNeedle } : undefined;

		this.store.dispatch(loadQuotes({ page, filters }));
	}

	handleClickRefreshPage() {
		location.reload();
	}

	handleClickCopy(quote: Quote) {
		const author = quote.author || appConfig.authorDefaultName;
		const textToCopy = `${quote.content}\n( ${author} )`;

		this.copyQuoteId = quote.id;

		if (this.clipboard.copy(textToCopy)) {
			this.copyStatusSbj$.next(CopyStatus.copied);
		} else {
			this.copyStatusSbj$.next(CopyStatus.error);
		}
	}

	getPaginatedItemIndex(index: number, currentPage?: number) {
		currentPage = currentPage || 1;

		return index + 1 + (currentPage - 1) * appConfig.quotesPerPage;
	}
}

<mat-card
	class="card"
	*ngIf="{
		isLoading: isLoading$ | async,
		isSearching: isSearchingSbj$ | async,
		pagination: pagination$ | async,
	} as asyncData"
>
	<h2 class="text-xl text-center mt-1/2 mb-1">Your saved quotes</h2>
	<app-error-message *ngIf="isError$ | async">
		Something didn't work. Please try to
		<button type="button" class="link-color-inherit" (click)="handleClickRefreshPage()">
			refresh the page</button
		>.
	</app-error-message>
	<mat-form-field *ngIf="showSearchField">
		<input
			matInput
			type="search"
			name="searchNeedle"
			placeholder="Search by keywords"
			[formControl]="searchField"
		/>
	</mat-form-field>
	<p
		*ngIf="!quotes.length; else dataTemplate"
		class="text-sm mt-1/2"
		[ngClass]="{ 'status-message': asyncData.isLoading || asyncData.isSearching }"
	>
		<ng-container [ngSwitch]="true">
			<ng-container *ngSwitchCase="asyncData.isSearching">Searching...</ng-container>
			<ng-container *ngSwitchCase="asyncData.isLoading && !asyncData.isSearching">
				Quotes are loading...
			</ng-container>
			<ng-container *ngSwitchDefault>No quotes found.</ng-container>
		</ng-container>
	</p>
	<ng-template #dataTemplate>
		<ol class="m-0 p-0" [ngClass]="{ 'opacity-50': asyncData.isLoading || asyncData.isSearching }">
			<app-quotes-list-item
				*ngFor="let quote of quotes; index as i"
				[quote]="quote"
				[itemIndex]="getPaginatedItemIndex(i, asyncData.pagination?.currentPage)"
				[copyStatus]="quote.id === copyQuoteId ? (copyStatusSbj$ | async) : null"
				(clickCopy)="handleClickCopy($event)"
			/>
		</ol>
		<app-pagination-menu
			[currentPage]="asyncData.pagination?.currentPage || 1"
			[numOfQuotes]="asyncData.pagination?.totalCount || 0"
			(clickPagination)="handleClickPagination($event)"
		/>
	</ng-template>
</mat-card>
