// fe-angular/src/app/pages/not-found-page/not-found-page.component.ts
import { Component } from "@angular/core";
import { pageItems } from "../../config/pageItems";

@Component({
	selector: "app-not-found-page",
	templateUrl: "./not-found-page.component.html",
	styleUrl: "./not-found-page.component.scss",
})
export class NotFoundPageComponent {
	readonly pageItems = pageItems;
}

<div class="h-screen flex flex-column flex-center gap-1/2">
	<h3 class="title m-0">Page Not Found</h3>
	<p>
		<a [routerLink]="pageItems.list.url">Back to Home</a>
	</p>
</div>

// fe-react/src/pages/NotFoundPage.tsx
import { Helmet } from "react-helmet-async";
import RouterLink from "../components/RouterLink/RouterLink";
import { pageItems } from "../config/pageItems";
import appConfig from "../config/appConfig";

export default function NotFoundPage() {
	return (
		<div className="h-full flex flex-col items-center justify-center gap-2">
			<Helmet>
				<title>{`404 | ${appConfig.appName}`}</title>
			</Helmet>
			<h3 className="text-xl">Page Not Found</h3>
			<p>
				<RouterLink to={pageItems.list.url}>Back to Home</RouterLink>
			</p>
		</div>
	);
}
