// fe-angular/src/app/pages/signup-page/signup-page.component.ts
import { Component } from "@angular/core";
import { pageItems } from "../../config/pageItems";

@Component({
	selector: "app-signup-page",
	templateUrl: "./signup-page.component.html",
	styleUrl: "./signup-page.component.scss",
})
export class SignupPageComponent {
	readonly pageItems = pageItems;
	showSuccessMessage = false;
}

<app-auth-layout>
	<p *ngIf="showSuccessMessage; else signupForm" class="text-lg text-center">
		<strong>Your account is almost ready.</strong>
		<br />
		<br />
		Please, check your mailbox, you should have received an email with instructions on how to
		activate your account.
		<br />
		<br />
		Thank you!
	</p>

	<ng-template #signupForm>
		<app-auth-form-title>{{ pageItems.signup.pageTitle }}</app-auth-form-title>
		<app-auth-form
			type="signup"
			[isLoading]="isLoading"
			[errorMessage]="errorMessage"
			(submitForm)="onSubmit($event)"
		/>
		<p>Do you already have an account? <a [routerLink]="pageItems.login.url">Log in</a></p>
	</ng-template>
</app-auth-layout>

// fe-react/src/pages/SignupPage.tsx
import { useState } from "react";
import { Helmet } from "react-helmet-async";
import AuthForm from "../components/AuthForm/AuthForm";
import AuthFormTitle from "../components/AuthFormTitle/AuthFormTitle";
import AuthLayout from "../components/AuthLayout/AuthLayout";
import RouterLink from "../components/RouterLink/RouterLink";
import appConfig from "../config/appConfig";
import { pageItems } from "../config/pageItems";
import { AuthFormValues } from "../components/AuthForm/AuthForm.types";
import { useAuth } from "../hooks/auth";

export default function SignupPage() {
	const [showSuccessMessage, setShowSuccessMessage] = useState(false);

	const { isMutating, errorMessage, doSignup } = useAuth();

	const handleOnSubmit = (formValues: AuthFormValues) => {
		doSignup(formValues, {
			onSuccess: () => setShowSuccessMessage(true),
		});
	};

	return (
		<AuthLayout>
			<Helmet>
				<title>{`${pageItems.signup.pageTitle} | ${appConfig.appName}`}</title>
			</Helmet>
			{!showSuccessMessage && <AuthFormTitle>{pageItems.signup.pageTitle}</AuthFormTitle>}
			{showSuccessMessage ? (
				<p className="text-lg text-center">
					<strong>Your account is almost ready.</strong>
					<br />
					<br />
					Please, check your mailbox, you should have received an email with instructions on how to
					activate your account.
					<br />
					<br />
					Thank you!
				</p>
			) : (
				<>
					<AuthForm
						type="signup"
						errorMessage={errorMessage}
						isLoading={isMutating}
						onSubmit={handleOnSubmit}
					/>
					<p>
						Do you already have an account? <RouterLink to={pageItems.login.url}>Log in</RouterLink>
					</p>
				</>
			)}
		</AuthLayout>
	);
}
