// fe-react/src/pages/ActivateAccountPage.tsx
import { ReactNode, useEffect, useMemo, useState } from "react";
import { Helmet } from "react-helmet-async";
import { pageItems } from "../config/pageItems";
import AuthLayout from "../components/AuthLayout/AuthLayout";
import { Navigate, useSearchParams } from "react-router-dom";
import { activateAccount } from "../services/AuthService";
import { isEmail } from "../utils/strings";
import { ResponseError } from "../types/error";
import { EMPTY_STRING, ErrorCodes } from "../constants";
import RouterLink from "../components/RouterLink/RouterLink";
import { useQuery } from "react-query";

export default function ActivateAccountPage() {
	const [searchParams] = useSearchParams();
	const [errorMessage, setErrorMessage] = useState<ReactNode>(null);

	const email = searchParams.get("email") || EMPTY_STRING;
	const activationToken = searchParams.get("activationToken") || EMPTY_STRING;
	const searchParamsExist = email && activationToken;
	const searchParamsAreValid = useMemo(
		() => isEmail(email) && /^[a-z0-9-]+$/i.test(activationToken),
		[email, activationToken]
	);

	const { isLoading } = useQuery<unknown, ResponseError>({
		enabled: searchParamsAreValid && !errorMessage,
		queryFn: () => activateAccount(email, activationToken),
		onError: error => {
			if (error.message === ErrorCodes.accountCannotBeActivated) {
				setErrorMessage(
					<>
						<strong>Your account cannot be activated.</strong>
						<br />
						Maybe your activation link has expired.
						<br />
						<br />
						Please, <RouterLink to={pageItems.signup.url}>try to sign up anew</RouterLink>.
					</>
				);
			} else {
				setErrorMessage(
					<>
						<strong>Something didn't work</strong> as expected,
						<br />
						please try again later.
					</>
				);
			}
		},
	});

	useEffect(() => {
		if (!searchParamsAreValid) {
			setErrorMessage(
				<>
					<strong>Your account cannot be activated.</strong>
					<br />
					Please check your activation link and retry.
				</>
			);
		}
	}, [searchParamsAreValid]);

	if (!searchParamsExist) {
		return <Navigate to={pageItems.signup.url} />;
	}

	return (
		<AuthLayout>
			<Helmet>
				<title>{pageItems.activateAccount.pageTitle}</title>
			</Helmet>
			<div className="text-lg text-center flex flex-grow justify-center items-center ">
				{errorMessage ? (
					<p>{errorMessage}</p>
				) : isLoading ? (
					<p>Your account is being activated...</p>
				) : (
					<p>
						Your account is active!
						<br />
						<RouterLink to={pageItems.login.url}>Log in</RouterLink>
					</p>
				)}
			</div>
		</AuthLayout>
	);
}

// fe-angular/src/app/pages/activate-account-page/activate-account-page.component.ts
import { Component } from "@angular/core";
import { ActivatedRoute, Router } from "@angular/router";
import { pageItems } from "../../config/pageItems";
import { ErrorCodes } from "../../constants";
import { AuthService } from "../../services/auth.service";
import { catchError, EMPTY } from "rxjs";
import { HttpErrorResponse } from "@angular/common/http";
import { isEmail } from "../../utils/strings";

@Component({
	selector: "app-activate-account-page",
	templateUrl: "./activate-account-page.component.html",
	styleUrl: "./activate-account-page.component.scss",
})
export class ActivateAccountPageComponent {
	isLoading = false;
	errorCode = 0;

	readonly pageItems = pageItems;
	readonly errorCodes = {
		invalidQueryParams: 1,
		accountCannotBeActivated: 2,
		serverError: 3,
	};

	constructor(
		private route: ActivatedRoute,
		private router: Router,
		private authService: AuthService
	) {
		this.route.queryParams.subscribe(({ email, activationToken }) => {
			if (email && activationToken) {
				this.triggerActivation(email, activationToken);
			} else {
				this.router.navigateByUrl(this.pageItems.signup.url);
			}
		});
	}

	triggerActivation(email: string, activationToken: string) {
		if (!isEmail(email) || /[^a-z0-9-]/i.test(activationToken)) {
			this.errorCode = this.errorCodes.invalidQueryParams;

			return;
		}

		this.isLoading = true;

		this.authService
			.activateAccount({ email, activationToken })
			.pipe(
				catchError(({ error }: HttpErrorResponse) => {
					this.isLoading = false;

					if (error?.message === ErrorCodes.accountCannotBeActivated) {
						this.errorCode = this.errorCodes.accountCannotBeActivated;
					} else {
						this.errorCode = this.errorCodes.serverError;
					}

					return EMPTY;
				})
			)
			.subscribe(() => {
				this.isLoading = false;
			});
	}
}

<app-auth-layout>
	<div class="text-lg text-center flex flex-grow justify-center items-center">
		<p *ngIf="isLoading; else statusMessage">Your account is being activated...</p>
		<ng-template [ngSwitch]="errorCode" #statusMessage>
			<p *ngSwitchCase="errorCodes.invalidQueryParams">
				<strong>Your account cannot be activated.</strong>
				<br />
				Please check your activation link and retry.
			</p>
			<p *ngSwitchCase="errorCodes.accountCannotBeActivated">
				<strong>Your account cannot be activated.</strong>
				<br />
				Maybe your activation link has expired.
				<br /><br />
				Please, <a [routerLink]="pageItems.signup.url">try to sign up anew</a>.
			</p>
			<p *ngSwitchCase="errorCodes.serverError">
				<strong>Something didn't work</strong> as expected,<br />please try again later.
			</p>
			<p *ngSwitchDefault>
				Your account is active!
				<br />
				<a [routerLink]="pageItems.login.url">Log in</a>
			</p>
		</ng-template>
	</div>
</app-auth-layout>
