// fe-angular/src/app/components/random-quote/random-quote.component.ts
import { Component, EventEmitter, OnInit, Output } from "@angular/core";
import { QuotesService } from "../../services/quotes.service";
import {
	BehaviorSubject,
	catchError,
	delay,
	EMPTY,
	filter,
	of,
	Subject,
	switchMap,
	takeUntil,
} from "rxjs";
import { QuoteWithoutServerGenFields } from "../../types/quotes";
import { Store } from "@ngrx/store";
import { AppState } from "../../store";
import { loadQuotes } from "../../store/actions/quotes.actions";
import appConfig from "../../config/appConfig";

@Component({
	selector: "app-random-quote",
	templateUrl: "./random-quote.component.html",
	styleUrl: "./random-quote.component.scss",
})
export class RandomQuoteComponent implements OnInit {
	isLoading = false;
	isSaving = false;
	isError = false;
	isSaveError = false;
	showView = true;
	quote: QuoteWithoutServerGenFields | null = null;

	@Output() onSave = new EventEmitter();
	@Output() onClickDismiss = new EventEmitter();

	readonly destroySbj$ = new Subject<boolean>();
	readonly showSavedSbj$ = new BehaviorSubject(false);

	constructor(
		private quotesService: QuotesService,
		private store: Store<AppState>
	) {}

	ngOnInit(): void {
		this.fetchRandomQuote();

		this.showSavedSbj$
			.pipe(
				filter(Boolean),
				switchMap(value => of(value).pipe(delay(appConfig.feedbackTimeout))),
				takeUntil(this.destroySbj$)
			)
			.subscribe(() => {
				this.showSavedSbj$.next(false);
				this.fetchRandomQuote();
			});
	}

	handleClickSave() {
		if (!this.quote) {
			return;
		}

		this.isSaving = true;
		this.isSaveError = false;

		this.quotesService
			.saveQuote(this.quote)
			.pipe(
				catchError(() => {
					this.isSaving = false;
					this.isSaveError = true;

					return EMPTY;
				})
			)
			.subscribe(() => {
				this.isSaving = false;

				this.showSavedSbj$.next(true);
				this.onSave.emit();
				this.store.dispatch(loadQuotes({ page: 1, refetch: true }));
			});
	}

	handleClickDismiss() {
		this.onClickDismiss.emit();
	}

	handleClickRefresh() {
		location.reload();
	}

	private fetchRandomQuote() {
		this.isLoading = true;
		this.isError = false;

		this.quotesService
			.getRandomQuote()
			.pipe(
				catchError(() => {
					this.isError = true;
					this.isLoading = false;

					return EMPTY;
				})
			)
			.subscribe(data => {
				this.isLoading = false;
				this.quote = data;
			});
	}
}

<mat-card class="card">
	<app-error-message *ngIf="isSaveError" [canBeDismissed]="true">
		Failed saving quote. Please, try again.
	</app-error-message>
	<ng-container *ngIf="!quote">
		<p *ngIf="isLoading" class="status-message text-sm">
			We are looking for a new quote to suggest you...
		</p>
		<div *ngIf="isError" class="text-sm flex justify-between gap-2">
			<div class="flex items-center">
				<p>
					Sorry, we couldn't find a new quote to suggest you. Please try to
					<!-- prettier-ignore -->
					<button type="button" class="link-color-inherit" (click)="handleClickRefresh()">refresh the page</button
					>.
				</p>
			</div>
			<button class="link" (click)="handleClickDismiss()">Dismiss</button>
		</div>
	</ng-container>

	<ng-container *ngIf="quote">
		<div
			*ngIf="{ showSaved: showSavedSbj$ | async } as asyncData"
			class="flex justify-between items-start gap-2"
		>
			<h3>
				You may like this quote by
				<em class="text-sky-900">
					{{ quote.author }}
				</em>
			</h3>
			<div class="text-sm flex items-center gap-1/2">
				<button
					class="link"
					[disabled]="isSaving || isLoading || asyncData.showSaved"
					(click)="handleClickDismiss()"
				>
					Dismiss
				</button>
				<span class="divider">|</span>
				<div class="text-sm font-medium sm:leading-7">
					<button
						type="button"
						class="save-button link"
						[disabled]="isSaving || isLoading || asyncData.showSaved"
						(click)="handleClickSave()"
					>
						<span *ngIf="asyncData.showSaved; else buttonText" class="feedback">Saved!</span>
						<ng-template #buttonText>
							{{ isSaving ? "Saving..." : "Save" }}
						</ng-template>
					</button>
				</div>
			</div>
		</div>
		<!-- prettier-ignore -->
		<blockquote class="quotes m-0 mt-1" [ngClass]="{ 'opacity-50': isLoading }">{{ quote.content }}</blockquote>
	</ng-container>
</mat-card>

// fe-react/src/components/RandomQuote/RandomQuote.tsx
import { useCallback, useState } from "react";
import Card from "../Card/Card";
import { useQuotes, useSaveQuote } from "../../hooks/quotes";
import ErrorMessage from "../ErrorMessage/ErrorMessage";
import RandomQuoteContent from "./RandomQuoteContent/RandomQuoteContent";
import RandomQuoteDismissButton from "./RandomQuoteDismissButton/RandomQuoteDismissButton";
import appConfig from "../../config/appConfig";
import { useTimer } from "../../hooks/timer";

export default function RandomQuote() {
	const { setTimer } = useTimer();
	const [showSaved, setShowSaved] = useState(false);

	const { randomQuoteQueryState } = useQuotes();
	const {
		isError: isSaveError,
		isLoading: isSaveLoading,
		mutate: triggerSave,
	} = useSaveQuote({
		onSuccess: () => {
			setShowSaved(true);
			setTimer(() => {
				setShowSaved(false);
				randomQuoteQueryState.refetch();
			}, appConfig.feedbackTimeout);
		},
	});

	const handleOnClickSave = useCallback(() => {
		if (randomQuoteQueryState.data) {
			triggerSave(randomQuoteQueryState.data);
		}
	}, [triggerSave, randomQuoteQueryState.data]);

	const handleOnClickDismiss = useCallback(() => {
		randomQuoteQueryState.updateEnabled(false);
	}, [randomQuoteQueryState]);

	const onClickRefresh = () => {
		location.reload();
	};

	if (!randomQuoteQueryState.isEnabled) {
		return null;
	}

	return (
		<Card testid="random-quote-card">
			{isSaveError && (
				<ErrorMessage canBeDismissed>Failed saving quote. Please, try again.</ErrorMessage>
			)}
			{randomQuoteQueryState.isLoading ? (
				<p className="text-sm text-gray-500">We are looking for a new quote to suggest you...</p>
			) : randomQuoteQueryState.isError || !randomQuoteQueryState.data ? (
				<div className="flex justify-between gap-6">
					<div className="flex items-center">
						<p className="text-sm ">
							{"Sorry, we couldn't find a new quote to suggest you. Please try to "}
							<button type="button" className="underline" onClick={onClickRefresh}>
								refresh the page
							</button>
							{"."}
						</p>
					</div>
					<RandomQuoteDismissButton className="self-start" onClick={handleOnClickDismiss} />
				</div>
			) : (
				<RandomQuoteContent
					saveButton={{
						disabled: isSaveLoading || showSaved,
						text: showSaved ? (
							<span className="text-green-700">Saved!</span>
						) : (
							isSaveLoading && "Saving..."
						),
					}}
					quote={randomQuoteQueryState.data}
					disabled={randomQuoteQueryState.isRefetching}
					onClickSave={handleOnClickSave}
					onClickDismiss={handleOnClickDismiss}
				/>
			)}
		</Card>
	);
}
